// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_Pagination.DataAccess.Core;

#nullable disable

namespace WebAPI_Pagination.Migrations
{
    [DbContext(typeof(AppContextFile))]
    partial class AppContextFileModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_Pagination.DataAccess.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A tool for writing or drawing with ink.",
                            Name = "Pen"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A tool for writing or drawing with graphite.",
                            Name = "Pencil"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A book of blank pages for writing notes.",
                            Name = "Notebook"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A tool for erasing pencil marks.",
                            Name = "Eraser"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A tool for measuring and drawing straight lines.",
                            Name = "Ruler"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A pen with a broad tip for marking.",
                            Name = "Marker"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A pen for highlighting text.",
                            Name = "Highlighter"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A device for fastening papers together.",
                            Name = "Stapler"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Small devices for holding papers together.",
                            Name = "Paper Clips"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A tool for cutting paper.",
                            Name = "Scissors"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A substance used for sticking things together.",
                            Name = "Glue"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A strip of material used for sticking things together.",
                            Name = "Tape"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A cover for holding loose sheets of paper.",
                            Name = "Binder"
                        },
                        new
                        {
                            Id = 14,
                            Description = "A cover for holding loose sheets of paper.",
                            Name = "Folder"
                        },
                        new
                        {
                            Id = 15,
                            Description = "A device for performing mathematical calculations.",
                            Name = "Calculator"
                        },
                        new
                        {
                            Id = 16,
                            Description = "A tool for sharpening pencils.",
                            Name = "Sharpener"
                        },
                        new
                        {
                            Id = 17,
                            Description = "A smooth, white surface for writing on with markers.",
                            Name = "Whiteboard"
                        },
                        new
                        {
                            Id = 18,
                            Description = "A soft, white limestone used for writing on blackboards.",
                            Name = "Chalk"
                        },
                        new
                        {
                            Id = 19,
                            Description = "A dark surface for writing on with chalk.",
                            Name = "Blackboard"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Small pieces of paper with a re-adherable strip of glue on their back.",
                            Name = "Sticky Notes"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Small cards used for recording and storing information.",
                            Name = "Index Cards"
                        },
                        new
                        {
                            Id = 22,
                            Description = "A device for printing documents.",
                            Name = "Printer"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Material for writing or printing on.",
                            Name = "Paper"
                        },
                        new
                        {
                            Id = 24,
                            Description = "A flat paper container for a letter or document.",
                            Name = "Envelope"
                        },
                        new
                        {
                            Id = 25,
                            Description = "A small piece of paper that you buy and stick onto an envelope or package to pay for mailing it.",
                            Name = "Stamp"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Elastic bands used for holding things together.",
                            Name = "Rubber Bands"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Small pins used for attaching papers to a board.",
                            Name = "Push Pins"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Small pins used for attaching papers to a board.",
                            Name = "Thumbtacks"
                        },
                        new
                        {
                            Id = 29,
                            Description = "A small board with a clip at the top for holding papers.",
                            Name = "Clipboard"
                        },
                        new
                        {
                            Id = 30,
                            Description = "A container for keeping office supplies organized.",
                            Name = "Desk Organizer"
                        },
                        new
                        {
                            Id = 31,
                            Description = "A piece of furniture used for storing files.",
                            Name = "File Cabinet"
                        },
                        new
                        {
                            Id = 32,
                            Description = "A device for printing labels.",
                            Name = "Label Maker"
                        },
                        new
                        {
                            Id = 33,
                            Description = "A pad for a computer mouse to move on.",
                            Name = "Mouse Pad"
                        },
                        new
                        {
                            Id = 34,
                            Description = "A device for typing on a computer.",
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = 35,
                            Description = "A screen for displaying computer output.",
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 36,
                            Description = "A small, portable device for storing data.",
                            Name = "USB Drive"
                        },
                        new
                        {
                            Id = 37,
                            Description = "A portable device for storing large amounts of data.",
                            Name = "External Hard Drive"
                        },
                        new
                        {
                            Id = 38,
                            Description = "A device for listening to audio.",
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Devices for playing sound.",
                            Name = "Speakers"
                        },
                        new
                        {
                            Id = 40,
                            Description = "A camera for video conferencing.",
                            Name = "Webcam"
                        },
                        new
                        {
                            Id = 41,
                            Description = "A device for recording or amplifying sound.",
                            Name = "Microphone"
                        },
                        new
                        {
                            Id = 42,
                            Description = "A device for projecting images onto a screen.",
                            Name = "Projector"
                        },
                        new
                        {
                            Id = 43,
                            Description = "A surface for displaying projected images.",
                            Name = "Screen"
                        },
                        new
                        {
                            Id = 44,
                            Description = "A device for connecting to the internet.",
                            Name = "Router"
                        },
                        new
                        {
                            Id = 45,
                            Description = "A device for connecting to the internet.",
                            Name = "Modem"
                        },
                        new
                        {
                            Id = 46,
                            Description = "A cable for connecting devices to a network.",
                            Name = "Ethernet Cable"
                        },
                        new
                        {
                            Id = 47,
                            Description = "A strip of sockets for plugging in multiple electrical devices.",
                            Name = "Power Strip"
                        },
                        new
                        {
                            Id = 48,
                            Description = "A long electrical cord for extending the reach of a power outlet.",
                            Name = "Extension Cord"
                        },
                        new
                        {
                            Id = 49,
                            Description = "A device for protecting electrical devices from power surges.",
                            Name = "Surge Protector"
                        },
                        new
                        {
                            Id = 50,
                            Description = "A device for charging batteries.",
                            Name = "Battery Charger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
